# -*- coding: utf-8 -*-
"""AI Practice.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GD66iBY3K9_NZPInhhTERaxRZVttE8bU
"""

import numpy as np

A = np.array([2,3])
print(A)

"""Magnitude"""

np.linalg.norm(A)

"""Addition"""

A = np.array([3,6])
B = np.array([8,9])
A+B

A = np.array([3,6])
B = np.array([8,9])
print(np.matmul(A,B)) #dot product
print(A*B)

"""Scalar Multiplication"""

C = np.array([3,6])
print(C*4)

"""Dot Product"""

A = np.array([3,6])
B = np.array([8,9])
print(np.dot(A,B))

"""Cosine Similarity"""

A = np.array([3,6])
B = np.array([8,9])

print(np.dot(A,B)/(np.linalg.norm(A)*np.linalg.norm(B)))

"""Orthogonal or not"""

A = np.array([1,0])
B = np.array([0,1])
print(np.dot(A,B))

"""These are perpendicular vectors so it s orthogonal vectors.

Vector Projection upon A,B
"""

A = np.array([3,6])
B = np.array([8,9])
print((np.dot(A,B)/np.dot(B,B))*B)

"""Check linear independence of vectors"""

A = np.array([3,6])
B = np.array([8,9])

np.linalg.matrix_rank(A,B) #Rank is < no of columns the result is dependent

A = np.array([3,6])
B = np.array([8,9])

print(2*A + 3*B)

A = np.array([[3,6],[9,2]])
B = np.array([[8,9],[3,5]])
C = (2*A) + (3*B)
print(C)
print()
print("Transpose\n",C.T) #Transpose

#Determinant
A = np.array([[3,6],[9,2]])
print(np.linalg.det(A))

#Identity Matrix of 3x3

np.eye(5)

#Inverse Matrix
A = np.array([[3,6],[9,2]])
B = np.array([[8,9],[3,5]])

np.linalg.inv(A) #Inverse of A

#Rank of matrix

A = np.array([[3,4],[2,4]])
np.linalg.matrix_rank(A)

#Trace of Matrix

A = np.array([[3,4],[2,4]])
np.trace(A)

#Check matrix is symmetric or not
A = np.array([[3,4],[2,4]])
print(np.all(A==A.T)) #rows and coloumn should be same

B = np.array([[3,3],[3,3]])
print(np.all(B==B.T))

A = np.array([[5, -10, -5],
              [2, 14, 2],
              [-4, -8, 6]])

print(np.linalg.eig(A))

from sympy import symbols, diff

x = symbols('x') #Derivative
diff(x**2 + 3*x)

x, y = symbols('x y') #Partial derivative with x

diff(x**2 + y**2 + 3*x,x)

diff(x**2 + y**2 + 3*x,y) #Partial derivative with y

from sympy import Matrix

f = x**2 + y**2
Matrix([[diff(f,x)],[diff(f,y)]])